# Generated by Django 5.2.4 on 2025-09-02 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='image_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
