# Generated by Django 5.2.4 on 2025-09-06 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_choice_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='image_size',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='medium', max_length=20),
        ),
    ]
