# Generated by Django 5.2.4 on 2025-09-06 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_choice_image_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='image_size',
            field=models.CharField(choices=[('tiny', 'Tiny'), ('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='medium', max_length=20),
        ),
    ]
