# Generated by Django 5.2.4 on 2025-09-06 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_choice_image_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='image_size',
            field=models.CharField(choices=[('inline', 'Inline Icon'), ('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='medium', max_length=20),
        ),
    ]
